
services:
  app:
    build: .
    environment:
      - DATABASE_URL=mysql://root:12345678@db:3306/library1
      - SMTP_HOST=smtp.ethereal.email
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - MAIL_FROM=pedbook <no-reply@pedbook.local>
      - PUBLIC_WEB_URL=http://localhost:8080
      - CLOUDINARY_CLOUD_NAME=ddfgsoh5g
      - CLOUDINARY_API_KEY=877612776229599
      - CLOUDINARY_API_SECRET=pDivBkF6G2A5PWLY_XihAA592kQ
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "8080:8082"
    command: >
      sh -c "
        echo 'Aguardando banco de dados...' &&
        npx prisma db push &&
        echo 'Schema sincronizado com sucesso!' &&
        echo 'Populando banco com dados iniciais...' &&
        npx prisma db seed &&
        echo 'Iniciando aplicação...' &&
        npm run start:prod
      "

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: library1
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3310:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p12345678"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 12345678
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
